package com.kmp

object CityList{

    private val cities = listOf(
        // Global cities
        "New York, United States",
        "Los Angeles, United States",
        "Chicago, United States",
        "London, United Kingdom",
        "Paris, France",
        "Berlin, Germany",
        "Tokyo, Japan",
        "Osaka, Japan",
        "Beijing, China",
        "Shanghai, China",
        "Hong Kong, China",
        "Sydney, Australia",
        "Melbourne, Australia",
        "Mumbai, India",
        "Delhi, India",
        "Bangalore, India",
        "Singapore, Singapore",
        "Dubai, United Arab Emirates",
        "Rome, Italy",
        "Milan, Italy",
        "Barcelona, Spain",
        "Madrid, Spain",
        "Toronto, Canada",
        "Vancouver, Canada",
        "Mexico City, Mexico",
        "São Paulo, Brazil",
        "Rio de Janeiro, Brazil",
        "Buenos Aires, Argentina",
        "Santiago, Chile",
        "Cairo, Egypt",
        "Istanbul, Turkey",
        "Moscow, Russia",
        "Saint Petersburg, Russia",
        "Seoul, South Korea",
        "Bangkok, Thailand",
        "Jakarta, Indonesia",
        "Kuala Lumpur, Malaysia",
        "Manila, Philippines",
        "Lagos, Nigeria",
        "Nairobi, Kenya",
        "Johannesburg, South Africa",
        "Cape Town, South Africa",
        "Riyadh, Saudi Arabia",
        "Jeddah, Saudi Arabia",
        "Doha, Qatar",
        "Athens, Greece",
        "Lisbon, Portugal",
        "Vienna, Austria",
        "Zurich, Switzerland",
        "Geneva, Switzerland",
        "Brussels, Belgium",
        "Amsterdam, Netherlands",
        "Stockholm, Sweden",
        "Oslo, Norway",
        "Helsinki, Finland",
        "Copenhagen, Denmark",
        "Budapest, Hungary",
        "Prague, Czech Republic",
        "Warsaw, Poland",
        "Krakow, Poland",
        "Bucharest, Romania",
        "Sofia, Bulgaria",
        "Belgrade, Serbia",
        "Zagreb, Croatia",
        "Ljubljana, Slovenia",
        "Bratislava, Slovakia",
        "Vilnius, Lithuania",
        "Riga, Latvia",
        "Tallinn, Estonia",

        // Additional Top 30 European Cities
        "Dublin, Ireland",
        "Edinburgh, United Kingdom",
        "Manchester, United Kingdom",
        "Venice, Italy",
        "Florence, Italy",
        "Naples, Italy",
        "Seville, Spain",
        "Valencia, Spain",
        "Bilbao, Spain",
        "Munich, Germany",
        "Hamburg, Germany",
        "Frankfurt, Germany",
        "Cologne, Germany",
        "Düsseldorf, Germany",
        "Copenhagen, Denmark",
        "Helsinki, Finland",
        "Oslo, Norway",
        "Gothenburg, Sweden",
        "Krakow, Poland",
        "Lisbon, Portugal",
        "Porto, Portugal",
        "Zürich, Switzerland",
        "Luxembourg, Luxembourg",
        "Bruges, Belgium",
        "Ghent, Belgium",
        "Reykjavik, Iceland",
        "Minsk, Belarus",
        "Chisinau, Moldova",
        "Tirana, Albania",
        "Skopje, North Macedonia"
    )


    fun getAllCountries(): List<String> {
        return cities
    }
}